Fix broken base image by specifying version
the latest base image caused the build to break as follows:
JetError: The command '/bin/sh -c apt-get update && apt-get install -y
build-essential python-dev python-pip python-setuptools python-wheel
libssl-dev
libxml2 libxml2-dev libcurl4-openssl-dev git bats && rm -rf
/var/lib/apt/lists/*' returned a non-zero code: 100

The following packages have unmet dependencies:
2016-11-08T16:40:05.000Z libcurl4-openssl-dev : Depends: libcurl3 (=
7.50.1-1) but 7.51.0-1 is to be installed
2016-11-08T16:40:05.014ZE: Unable to correct problems, you have held
broken packages.
2016-11-08T16:40:05.245ZRemoving intermediate container b3aac7da509e

The error above seems to be characteristic of R

This fixes the base image. It should be updated every-so-often in the
future, but is best to fix the dependency so builds are more assured to
work.